// src/constants/facilityIcons.ts
import { IconDefinition } from "@fortawesome/fontawesome-svg-core";
import {
    faUtensils,
    faCoffee,
    faVideo,
    faTree,
    faDumbbell,
    faCouch,
    faSwimmingPool,
    faHotTub,
    faWifi,
    faTv,
    faKitchenSet,
    faSnowflake,
    faSoap,
    faHandsWash,
    faBath,
    faShower,
    faTable,
    faTshirt,
    faMugSaucer,
    faPaw,
    faSmoking,
    faSmokingBan,
    faFire,
    faBriefcase,
    faMartiniGlass,
    faParking,
    faKitMedical,
    faFireExtinguisher,
    faBed,
    faDoorOpen,
    faWindowRestore,
    faTemperatureHalf,
    faChair,
    faPlug,
    faBolt,
    faPhone,
    faUmbrellaBeach,
    faCity,
    faBabyCarriage,
    faWheelchair,
    faBellConcierge,
    faBroom,
    faSpa,
    faBookOpen,
    faDice,
    faMusic,
    faLock,
    faShield
} from "@fortawesome/free-solid-svg-icons";
export const facilityIcons: Record<string, IconDefinition> = {
    'bbq': faUtensils,
    'cafe': faCoffee,
    'cctv': faVideo,
    'garden': faTree,
    'gym': faDumbbell,
    'weekend': faCouch,
    'pool': faSwimmingPool,
    'hot_tub': faHotTub,
    'wifi': faWifi,
    'tv': faTv,
    'kitchen': faKitchenSet,
    'ac_unit': faSnowflake,
    'local_laundry_service': faSoap,
    'washing_machine': faSoap,
    'dry': faHandsWash,
    'bathtub': faBath,
    'shower': faShower,
    'desk': faTable,
    'iron': faTshirt,
    'coffee': faMugSaucer,
    'refrigerator': faKitchenSet,
    'microwave': faKitchenSet,
    'park': faTree,
    'pets': faPaw,
    'smoking': faSmoking,
    'smoke_free': faSmokingBan,
    'grill': faFire,
    'business': faBriefcase,
    'restaurant': faUtensils,
    'bar': faMartiniGlass,
    'parking': faParking,
    'medical_services': faKitMedical,
    'fire_extinguisher': faFireExtinguisher,
    'videocam': faVideo,
    'bed': faBed,
    'door_sliding': faDoorOpen,
    'window': faWindowRestore,
    'thermostat': faTemperatureHalf,
    'chair': faChair,
    'fridge': faKitchenSet,
    'outlet': faPlug,
    'charging_station': faBolt,
    'phone': faPhone,
    'beach_access': faUmbrellaBeach,
    'city_view': faCity,
    'non_smoking': faSmokingBan,
    'baby_care': faBabyCarriage,
    'accessible': faWheelchair,
    'room_service': faBellConcierge,
    'cleaning_services': faBroom,
    'spa': faSpa,
    'library': faBookOpen,
    'games': faDice,
    'music': faMusic,
    'safe': faLock,
    'security': faShield
};
